# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'vanilla' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'Google/SignIn'
  # Pods for vanilla

end
